/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.stuffthathappens.games;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int accelerometer_btn=0x7f050006;
        public static final int accuracy_label=0x7f050000;
        public static final int calibrate_button=0x7f050004;
        public static final int sensor_list=0x7f050009;
        public static final int sensor_list_btn=0x7f050005;
        public static final int sensor_name=0x7f050007;
        public static final int sensor_supported=0x7f050008;
        public static final int x_label=0x7f050001;
        public static final int y_label=0x7f050002;
        public static final int z_label=0x7f050003;
    }
    public static final class layout {
        public static final int accel=0x7f030000;
        public static final int home=0x7f030001;
        public static final int list_item_sensor=0x7f030002;
        public static final int sensors=0x7f030003;
    }
    public static final class string {
        public static final int accelerometer=0x7f040001;
        public static final int accuracy_high=0x7f040006;
        public static final int accuracy_low=0x7f040004;
        public static final int accuracy_medium=0x7f040005;
        public static final int accuracy_unknown=0x7f040002;
        public static final int accuracy_unreliable=0x7f040003;
        public static final int app_name=0x7f040000;
        public static final int calibrate=0x7f040009;
        public static final int no_accelerometer=0x7f040007;
        public static final int sensor_list=0x7f040008;
    }
}
